name: 'Auto Assign'

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@3f4d16b9e7887503a0fef2c3ccd80aa64cad8f31
