name: Check Size

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

permissions:
  contents: read

jobs:
  check_size:
    name: Check Size
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 1

      - name: Check large files
        uses: actionsdesk/lfs-warning@4b98a8a5e6c429c23c34eee02d71553bca216425
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filesizelimit: '1048576'
          exclusionPatterns: |
            deploy/helm-charts
            manager/console
            client
